### ISSUE TITLE
Invalid Probes

### ISSUE THREAD

**Issue by Fissium** [devops-ia/helm-cruise-control#12]
### Describe the bug a clear and concise description of what the bug is.

liveness, rediness and startup probes are invalid:
```
livenessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 180
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
```

### What's your helm version?

3.16.3

### What's your kubectl version?

1.31.2

### Chart version

1.1.4

### Explain bug

The probes configuration includes an invalid `enabled` field, which is not recognized in Kubernetes. This causes deployment errors.

### Enter the command that you execute when chart failing/misfunctioning

I use argocd
